# Docker contianer used to seed MongoDB with data

# Extends MongoDB
# Note - the Mongo database in this container isn't used actually used at all.
# We use the `mongoimport` command line utility on this container to populate the other Mongo container with data.
FROM mongo

# Copies seed/*.json
<%- copyStatements %>

# Imports each collection into MongoDB
<%- mongoImports %>